# Header
menu:
  Home: /
  Docs: /docs
rss: /atom.xml

# Content
excerpt_link: Read More

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:
